#!/usr/bin/env bash

source './util'

packages=(
    "arc"
    "visual-studio-code"
    "google-chrome"
    "iterm2"
    "postman"
    "mongodb-compass"
    "orbstack"
    "warp"
    "raycast"
    "notion"
    "notion-calendar"
    "rectangle"
    "discord"
    "figma"
    "font-jetbrains-mono"
    "obsidian"
    "github"
)

install_apps "${packages[@]}"
