#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"

source "$SCRIPT_DIR/util"

packages=(
    "neovim"
)

install_packages "${packages[@]}"

create_symlink "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"
